sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip python-virtualenv libevent-dev
script:
  - mvn test
  - mvn package
  - ./src/test/resources/run-glacier-tests.sh
